updated

diff --git a/modules/core b/modules/core
--- a/modules/core
+++ b/modules/core
@@ -30,64 +30,64 @@ SDAAS_SIGNATURE=${SDAAS_SIGNATURE:-"SDaaS $SDAAS_APPLICATION_ID $SDAAS_VERSION"}
 ## Core functions definition
 ################################################################################
 
+
 sd_log() {
 	# parse and validate inputs
-	local PRIORITY=5
-	local SIZE=1024
-	local FILE MESSAGE
-	local OPTIND opt; while getopts ":f:p:S:" opt; do
+	local OPT_PRIORITY=5
+	local OPT_SIZE=1024
+	local OPT_FILE=""
+    local OPTIND opt; while getopts ":f:p:S:" opt; do
         case "${opt}" in
-            p) PRIORITY="${OPTARG}" ;;
-            f) FILE="$(readlink -f "${OPTARG}")" ;;
+            f) OPT_FILE="$(readlink -f "${OPTARG}")" ;;
+            p) OPT_PRIORITY="${OPTARG}" ;;
             S) 
-				(( OPTARG += 0 ))  # cast to integer
-				if [[ $OPTARG -gt 0 ]]; then 
-					SIZE=$OPTARG;
+				if [[ $(( OPTARG )) -gt 0 ]]; then 
+					OPT_SIZE=$OPTARG;
 				fi
                 ;;
+			*) sd_log -p ERROR "Invalid option: -$OPTARG ." ; return 1 ;;
         esac
-    done; shift $((OPTIND-1))	
-
-	MESSAGE="$@"
-	MESSAGE="${MESSAGE:0:$SIZE}" 
+    done; shift $((OPTIND-1))
+	local ARG_MESSAGE="$1"
+	ARG_MESSAGE="${ARG_MESSAGE:0:$OPT_SIZE}" 
 
 	# normalize priority level
-	case "${PRIORITY^^}" in
-		CRITICAL | 2) PRIORITY=2 ;;
-		ERROR | 3) PRIORITY=3 ;;
-		WARNING | 4) PRIORITY=4 ;;
-		NOTICE | 5) PRIORITY=5 ;;
-		INFORMATIONAL | 6) PRIORITY=6 ;;
-		DEBUG | 7) PRIORITY=7 ;;
+	case "${OPT_PRIORITY^^}" in
+		CRITICAL | 2) OPT_PRIORITY=2 ;;
+		ERROR | 3) OPT_PRIORITY=3 ;;
+		WARNING | 4) OPT_PRIORITY=4 ;;
+		NOTICE | 5) OPT_PRIORITY=5 ;;
+		INFORMATIONAL | 6) OPT_PRIORITY=6 ;;
+		DEBUG | 7) OPT_PRIORITY=7 ;;
 		* ) 
-		    MESSAGE="invalid log priority $PRIORITY"
-			PRIORITY=3
+		    ARG_MESSAGE="invalid log priority $OPT_PRIORITY"
+			OPT_PRIORITY=3
 			;;
 	esac
 	
 	# normalize priority level mnemonic
 	local mnemonic
-	case "${PRIORITY^^}" in
+	case "${OPT_PRIORITY}" in
 		2) mnemonic=CRITICAL ;;
 		3) mnemonic=ERROR ;;
 		4) mnemonic=WARNING ;;
 		5) mnemonic=NOTICE ;;
 		6) mnemonic=INFORMATIONAL ;;
 		7) mnemonic=DEBUG ;;
-		* ) mnemonic="$PRIORITY"
+		* ) mnemonic="$OPT_PRIORITY"
 			;;
 	esac
 
-	# format and print log message
-	if [[ "$PRIORITY" -le "$SD_LOG_PRIORITY" ]]; then 
-		echo "[$mnemonic] [sdaas-$$ ${FUNCNAME[1]}] "$MESSAGE"" >&2
-		if [[ -r "$FILE" ]]; then
-			local file_size=$(stat -c %s "$FILE")
+	# format and print log ARG_MESSAGE
+	if [[ "$OPT_PRIORITY" -le "$SD_LOG_PRIORITY" ]]; then 
+		echo "[$mnemonic] [sdaas-$$ ${FUNCNAME[1]}] "$ARG_MESSAGE"" >&2
+		if [[ -r "$OPT_FILE" ]]; then
+			local file_size=$(stat -c %s "$OPT_FILE")
 			if [[ "$file_size" -gt 1024 ]]; then
-				head -c 1024 "$FILE" >&2
-				echo "...see more info at $FILE (size=$file_size bytes)" >&2
+				head -c 1024 "$OPT_FILE" >&2
+				echo "...see more info at $OPT_FILE (size=$file_size bytes)" >&2
 			else
-				cat "$FILE" >&2
+				cat "$OPT_FILE" >&2
 			fi
 		fi
 	fi
@@ -144,8 +144,8 @@ sd_curl() {
 
 
 sd_rapper() {
-	# sd_log -p DEBUG "executing rapper -gwq $@"
-	rapper -gwq \
+	# sd_log -p DEBUG "executing rapper -wq $@"
+	rapper -wq \
 		-f 'xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"' \
 		-f 'xmlns:owl="http://www.w3.org/2002/07/owl#"' \
 		-f 'xmlns:foaf="http://xmlns.com/foaf/0.1/"' \
@@ -157,7 +157,7 @@ sd_rapper() {
 		-f 'xmlns:void="http://rdfs.org/ns/void#"' \
 		-f 'xmlns:xsd="http://www.w3.org/2001/XMLSchema#"' \
 		-f 'xmlns:kees="http://linkeddata.center/kees/v1#"' \
-		-f 'xmlns:sdaas="http://linkeddata.center/sdaas/v4#"' \
+		-f 'xmlns:sdaas="http://linkeddata.center/sdaas/reference/v4#"' \
 		"$@"
 }
 
@@ -165,7 +165,7 @@ sd_rapper() {
 sd() {
 	local abortOnFail=${SD_ABORT_ON_FAIL:-false}
 	local help=false
-	local OPTIND opt ; while getopts ":hA" opt; do 
+	while getopts ":hA" opt; do 
         case "${opt}" in
 			h) help=true ;;
 			A) abortOnFail=true ;;
@@ -223,27 +223,24 @@ sd_core_version() {
 
 
 sd_core_ontology() {
-	local out_format="ntriples"
+	# parse and validate inputs
+   	local OPT_OUTPUT_FORMAT="ntriples"
     local OPTIND opt; while getopts ":o:" opt; do
         case "${opt}" in
-            o) out_format="${OPTARG}" ;;
-			*) 
-				sd_log -p ERROR "Invalid option: -$OPTARG ." 
-				return 1 
-				;;
+            o) OPT_OUTPUT_FORMAT="${OPTARG}" ;;
+			*) sd_log -p ERROR "Invalid option: -$OPTARG ." ; return 1 ;;
         esac
     done; shift $((OPTIND-1))
-
-    sd_validate out_format "^(rdfxml|ntriples|turtle)$" || return 1
+	sd_validate OPT_OUTPUT_FORMAT "^(rdfxml|ntriples|turtle)$" || return 1
 
 	function get_triples {
 		local files_array="$(find $SDAAS_ETC -type f \( -name "*.rdf" -o -name "*.nt" -o -name "*.ttl" \))"
 		for file in "${files_array[@]}"; do
-			sd_rapper -I "urn:sdaas:tbox" -O "urn:sdaas:tbox" "$file" || sd_abort "Internal error, invalid tbox $file"
+			sd_rapper -g -I "urn:sdaas:tbox" -o ntriples "$file" || sd_abort "Internal error, invalid tbox $file"
 		done
 	}
 
-	get_triples | sd_rapper -I "urn:sdaas:tbox" -o "$out_format" -O "urn:sdaas:tbox"  -
+	get_triples | sd_rapper -i ntriples -o "$OPT_OUTPUT_FORMAT"  - "urn:sdaas:tbox"
 }
 
 ################################################################################
