updated

diff --git a/modules/view b/modules/view
--- a/modules/view
+++ b/modules/view
@@ -19,7 +19,7 @@ sd_view_config() {
 
 	_view_config_compgen SDAAS_
 	_view_config_compgen SD_
-	_view_config_compgen STORE_
+	_view_config_compgen STORE
 }
 
 
@@ -61,3 +61,30 @@ sd_view_module() {
 	done
 }
 
+
+
+sd_view_version() {
+	echo "$SDAAS_VERSION"
+}
+
+
+sd_view_ontology() {
+	# parse and validate inputs
+   	local OPT_OUTPUT_FORMAT="ntriples"
+    local OPTIND opt; while getopts ":o:" opt; do
+        case "${opt}" in
+            o) OPT_OUTPUT_FORMAT="${OPTARG}" ;;
+			*) sd_log -p ERROR "Invalid option: -$OPTARG ." ; return 1 ;;
+        esac
+    done; shift $((OPTIND-1))
+	sd_validate OPT_OUTPUT_FORMAT "^(rdfxml|ntriples|turtle)$" || return 1
+
+	function get_triples {
+		local files_array="$(find $SDAAS_ETC -type f \( -name "*.rdf" -o -name "*.nt" -o -name "*.ttl" \))"
+		for file in "${files_array[@]}"; do
+			sd_rapper -g -I "urn:sdaas:tbox" -o ntriples "$file" || sd_abort "Internal error, invalid tbox $file"
+		done
+	}
+
+	get_triples | sd_rapper -i ntriples -o "$OPT_OUTPUT_FORMAT"  - "urn:sdaas:tbox"
+}
